# Generated by Django 4.1.1 on 2022-11-01 06:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0004_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('ST', 'Stationary'), ('GR', 'Groceries'), ('SN', 'Snacks'), ('FV', 'fruits and vegetables'), ('HE', 'home essentials'), ('TI', 'toiletries'), ('HG', 'hygiene'), ('FO', 'food'), ('MD', 'medicines')], max_length=2),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_id', models.CharField(max_length=100)),
                ('paid', models.BooleanField(default=b'I00\n')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
